//! Golden round-trip + snapshot tests over real-shaped fixtures (docs/13).
//!
//! parse → serialize → parse must be model-equal; our own serializer output is
//! byte-stable; insta captures the canonical serialized form so regressions in
//! ordering/encoding are caught.

use keylayout_core::modifiers::ModMask;
use keylayout_core::{build_snapshot, parse_keylayout, serialize_keylayout, EncodeOpts};

const FIXTURES: &[(&str, &str)] = &[
    ("dead", include_str!("fixtures/sample_dead.keylayout")),
    ("iso", include_str!("fixtures/sample_iso.keylayout")),
    ("astral", include_str!("fixtures/sample_astral.keylayout")),
    // Real Ukelele-generated file: 8 keymaps, 872 keys, complex modifier map,
    // DOCTYPE SYSTEM form, leading comments, group=126.
    (
        "russian",
        include_str!("fixtures/russian_pc_ukelele.keylayout"),
    ),
];

fn fixture(name: &str) -> &'static str {
    FIXTURES.iter().find(|(n, _)| *n == name).unwrap().1
}

#[test]
fn round_trip_model_equal_all_fixtures() {
    for (name, xml) in FIXTURES {
        let kb = parse_keylayout(xml).unwrap_or_else(|e| panic!("{name}: {e}"));
        let out = serialize_keylayout(&kb, &EncodeOpts::default());
        let kb2 = parse_keylayout(&out).unwrap_or_else(|e| panic!("{name} reparse: {e}"));
        let mut a = kb.clone();
        a.update_maxout();
        assert_eq!(a, kb2, "{name} not model-equal after round-trip");
    }
}

#[test]
fn serializer_byte_stable_all_fixtures() {
    for (name, xml) in FIXTURES {
        let kb = parse_keylayout(xml).unwrap();
        let out1 = serialize_keylayout(&kb, &EncodeOpts::default());
        let kb2 = parse_keylayout(&out1).unwrap();
        let out2 = serialize_keylayout(&kb2, &EncodeOpts::default());
        assert_eq!(out1, out2, "{name} not byte-stable");
    }
}

#[test]
fn golden_serialized_dead() {
    let kb = parse_keylayout(fixture("dead")).unwrap();
    let out = serialize_keylayout(
        &kb,
        &EncodeOpts {
            code_non_ascii: true,
        },
    );
    insta::assert_snapshot!("serialized_dead", out);
}

#[test]
fn golden_serialized_iso() {
    let kb = parse_keylayout(fixture("iso")).unwrap();
    let out = serialize_keylayout(
        &kb,
        &EncodeOpts {
            code_non_ascii: true,
        },
    );
    insta::assert_snapshot!("serialized_iso", out);
}

#[test]
fn astral_round_trips_codepoints() {
    let kb = parse_keylayout(fixture("astral")).unwrap();
    let snap = build_snapshot(&kb, 0, ModMask::empty(), "none");
    assert_eq!(snap.keys[0].output.as_deref(), Some("😀"));
    assert_eq!(snap.keys[0].code_points, vec![0x1F600]);
    // flag = two regional indicators
    assert_eq!(snap.keys[1].code_points, vec![0x1F1FA, 0x1F1F8]);
    // name with entity decoded
    assert_eq!(snap.keyboard_name, "Emoji & Astral");
}

#[test]
fn real_russian_layout_round_trips_and_resolves() {
    let kb = parse_keylayout(fixture("russian")).unwrap();
    assert_eq!(kb.name, "Russian - PC 2026");
    assert_eq!(kb.group, 126);
    assert_eq!(kb.id, -1251);
    let set = kb.keymap_set("a8").unwrap();
    assert_eq!(set.maps.len(), 8);
    let total: usize = set.maps.iter().map(|m| m.keys.len()).sum();
    assert_eq!(total, 872);
    // validation is clean on this real file (no false positives)
    assert!(keylayout_core::validate(&kb).is_empty());
    // base layer (defaultIndex resolved) produces Cyrillic output
    let snap = build_snapshot(&kb, 0, ModMask::empty(), "none");
    assert!(snap.keys.iter().any(|k| k
        .output
        .as_deref()
        .map(|s| s.chars().any(|c| ('\u{0400}'..='\u{04FF}').contains(&c)))
        .unwrap_or(false)));
}

#[test]
fn real_russian_layout_preserves_header_comments() {
    let kb = parse_keylayout(fixture("russian")).unwrap();
    let header = kb.comments.before.get("header").expect("header comments");
    assert!(header.iter().any(|c| c.contains("kluchrtoxml")));
    assert!(header.iter().any(|c| c.contains("Ukelele")));
    // survive a round-trip
    let out = serialize_keylayout(&kb, &EncodeOpts::default());
    assert!(out.contains("Generated by kluchrtoxml"));
    let kb2 = parse_keylayout(&out).unwrap();
    assert_eq!(kb.comments, kb2.comments);
}

#[test]
fn iso_snapshot_resolution() {
    let kb = parse_keylayout(fixture("iso")).unwrap();
    // option layer (index 2): code 0 → å, inherited code 10 → §
    let opt = build_snapshot(&kb, 0, ModMask::empty().with(ModMask::OPTION_L), "none");
    assert_eq!(opt.modifier_index, 2);
    assert_eq!(opt.keys[0].output.as_deref(), Some("å"));
    assert_eq!(opt.keys[10].output.as_deref(), Some("§"));
    assert!(opt.keys[10].inherited);
}
